### ISSUE TITLE
Update docket container to latest version

### ISSUE THREAD

**Issue by Nick8197** [alpacahq/pylivetrader#101]
Hello can you update the docker containers in pylivetrader to most recent versions?  Looks like it’s still on 0.25      
 
https://hub.docker.com/r/alpacamarkets/pylivetrader

**Comment by ttt733** [comment]
Will be doing so later this evening or tomorrow. I left it a couple versions behind to avoid the changes for power accounts reaching more users than necessary, but now some new features have come in that need to be distributed.
