### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'current_ratio'

### ISSUE THREAD

**Issue by Riisberg** [alpacahq/pylivetrader#103]
Link to code: https://github.com/alpacahq/pylivetrader/blob/master/examples/graham-fundamentals/GrahamFundamentals.py 
When I run the code, I get this error. I have not modified the code in any way, so I do not know why this problem occurs. 
AttributeError: 'DataFrame' object has no attribute 'current_ratio'

**Comment by shlomikushchi** [comment]
this sample code is not a part of pylivetrader anymore.
