### ISSUE TITLE
Reducing Huge Memory Footprint For Heroku

### ISSUE THREAD

**Issue by tbc399** [alpacahq/pylivetrader#104]
This is of course not a bug, but I'm wondering if there's a any way to make the memory footprint of a running algo smaller. Currently, I've tried running my algo on Heroku against the paper trading api in Alpaca, and I'm seeing that Heroku is flagging the memory usage. From what I can tell, the app is hitting something just north of 800MB, and Heroku limits ram to 512MB for anything that you don't have to shell out the bucks for. Now, granted, I do have a couple of factors that are acting on 6 month windows of daily data, so that might have something to do with it, but is there any way to make things more efficient?

**Comment by shlomikushchi** [comment]
have you tried using the docker image?

**Comment by tbc399** [comment]
No not yet, but I'll give that a shot, and we'll see what happens. Any rationale as to why that might help out?

**Comment by shlomikushchi** [comment]
just a matter of isolation. it will give an easier way to know exactly what is your memory consumption in different scenarios.
you could run `docker stats` and you can understand the memory used in different stages of your exection. 
I cannot execute your code (don't have it) but maybe I can help you get insights about what you could do.

**Comment by shlomikushchi** [comment]
closing the issue for inactivity
