### ISSUE TITLE
Seemingly hanging after pylivetrader run -f algo.py

### ISSUE THREAD

**Issue by CapitalZe** [alpacahq/pylivetrader#106]
Ubuntu 16.04 Via VMWare on Mac.

I set my env variables accordingly and run:

`pylivetrader run -f algo.py`

Thereafter this is the readout:

`[2019-06-11 08:24:47.971239] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
`

It then hangs here for a long time; hours.
What seems to be the issue here?

For reference the code in algo.py is the example pylivetrader algorithm:

```from pylivetrader.api import order_target, symbol
from pylivetrader.api import *


def initialize(context):
    context.i = 0
    context.asset = symbol('AAPL')

def handle_data(context, data):
    # Compute averages
    # data.history() has to be called with the same params
    # from above and returns a pandas dataframe.
    short_mavg = data.history(context.asset, 'price', bar_count=100, frequency="1m").mean()
    long_mavg = data.history(context.asset, 'price', bar_count=300, frequency="1m").mean()`

    # Trading logic
    if short_mavg > long_mavg:
        # order_target orders as many shares as needed to
        # achieve the desired number of shares.
        order_target(context.asset, 100)
    elif short_mavg < long_mavg:
        order_target(context.asset, 0)

**Comment by CapitalZe** [comment]
Update:

After letting it run for almost three hours this is thrown back:

` raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/1560249900000/1560261960000?unadjusted=False&apiKey=PKQZUHM7F5CHJD7LHJAD
[2019-06-11 14:06:00.896216] WARNING: Executor: Continuing execution`

I know for a fact the Key and ID are correct, as well as the base URL endpoint (i'm using https://paper-api.alpaca.markets). I've tried using config.yaml and environment variables but face this error each time.
I also have regenerated the key and ID numerous times.

My estimation is that everything is working fine except the Alpaca API, as my credentials are being refused, yet I cannot identify why.

**Comment by ttt733** [comment]
Hello @CapitalZe , please note that Polygon data, which Pylivetrader is dependent on, is only available freely to users with funded Alpaca brokerage accounts. Have you funded your account yet? If so and it's still not authenticating you, please try generating your live trading keys and then trying your paper keys again.

**Comment by CapitalZe** [comment]
Hello @ttt733, Thank you for the information.

I was not aware of that and have tried to set up and fund my account without luck. I am not a US citizen and therefore do not have a social security number or zip code that satisfies the data form on Alpaca.

Further digging revealed the IEX option listed on Alpaca as found [here](https://docs.alpaca.markets/api-documentation/web-api/market-data/#which-api-should-i-use).
You don't happen to know how to implement the IEX API via pylivetrader do you?

**Comment by ttt733** [comment]
Pylivetrader does not yet support IEX data as an alternative to Polygon data. If we add support for a free data source it will likely be the Alpaca data API, as IEX Cloud has become less free lately.
