### ISSUE TITLE
"Error " Sector name: Basic Materials

### ISSUE THREAD

**Issue by jordisanchezcarbonell** [alpacahq/pylivetrader#107]
I have this error:
raise ValueError("Invalid sector name: {}".format(sector))
ValueError: Invalid sector name: Basic Materials
[2019-07-08 17:30:05.511926] WARNING: Executor: Continuing execution

**Comment by ttt733** [comment]
Hello @jordisanchezcarbonell , we'd need to see more of the code you're using in order to help. Please reopen if you wish to share the code that attempts to look up that sector.
