### ISSUE TITLE
Using IEX instead of Alpaca

### ISSUE THREAD

**Issue by CapitalZe** [alpacahq/pylivetrader#109]
Has anyone successfully used IEX instead of Alpaca?

I see various references to it in the code and have failed in getting it to run myself.

My goal is to run pylivetrader locally and display trading information via pandas locally, as opposed to going to Alpaca overview.

I'm quite stuck on this, any help would be greatly appreciated.

**Comment by sammerry** [comment]
I have an open PR to fix IEX finance in the pipeline. Im not sure if its the same bug your facing.
https://github.com/alpacahq/pipeline-live/pull/14

**Comment by ttt733** [comment]
Hello, please see the information in the readme for pipeline-live regarding the use of IEX Cloud: https://github.com/alpacahq/pipeline-live#iex-data-source-api

Note that there is some additional setup required and that your use of the IEX API with pipeline-live may fall outside of what's supported by their free pricing tier.
