### ISSUE TITLE
data.history throwing error due to improper timestamp to datetime conversion

### ISSUE THREAD

**Issue by reaganmcf** [alpacahq/pylivetrader#112]
Every `data.history` call in my algorithm throws errors due to `pylivetrader/backend/alpaca.py` attempting to convert timestamps to datetimes for the dataframe index, but the dataframe's index is already in datetime format.  This is located
```py
# convert timestamps to datetimes
# astype is necessary to deal with empty result
df.index = pd.to_datetime(
    df.index.astype('int64') * 1000000,
    utc=True,
).tz_convert('America/New_York')
df.index.name = 'timestamp'
```

**Comment by reaganmcf** [comment]
It seems that the new polygon v2 agg method does not return timestamps, but string date times.

Changing `df.index.astype('int64') * 1000000` to `df.index.astype('str')` seems to have worked.

I will be submitting a Pull Request if I don't find any other issues with this fix

**Comment by reaganmcf** [comment]
https://github.com/alpacahq/pylivetrader/pull/113

**Comment by ttt733** [comment]
Merged the PR, will be releasing later today when I have addressed some other issues. Thanks!
