### ISSUE TITLE
Installation Error via PIP

### ISSUE THREAD

**Issue by CapitalZe** [alpacahq/pylivetrader#117]
I took a couple weeks off of pylivetrader, which I had up and running.

Unfortunately, I lost access to my working venv wherein everything worked fine (someone unintentionally cleared my drive containing it.

Nothing else has changed, so far as I can identify, yet now when I follow the standard protocol to install pylivetrader in the venv I am faced with the following:

`ERROR: Command errored out with exit status 1: /home/XXX/bin/python3 /home/dt-nicholas/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ge33c4yz/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython 'numpy==1.9.3; python_version=='"'"'3.5'"'"'' 'numpy==1.12.1; python_version=='"'"'3.6'"'"'' 'numpy==1.13.1; python_version>='"'"'3.7'"'"'' Check the logs for full command output.
`

I'm not finding anything which solves this. If anyone has a better idea of what is going on I'd be very grateful for sharing.

Cheers!

**Comment by CapitalZe** [comment]
I just noticed

**Comment by CapitalZe** [comment]
FYI, this was a python issue. I removed all python versions globally and then reinstalled 3.5 only in my venv.

The new error is this:

`ERROR: No matching distribution found for websockets>=8.0 `

I'm looking into it now, will post what I learn.

**Comment by CapitalZe** [comment]
I still haven't solved this and it's also raised [here](https://github.com/alpacahq/alpaca-trade-api-python/issues/112).

If anyone can point me in the right direction it'd be great!

**Comment by ttt733** [comment]
Hello! The only supported version of Python for pylivetrader installation at the moment is 3.6, due to some issues with old zipline dependencies. I just went through the following steps to install pylivetrader, and it was working. Please try using python 3.6 and reopen with more information if it's not working for you.

```
$ python3.6 -m venv venv
$ source venv/bin/activate
(venv)$ python --version
Python 3.6.7
pip install pylivetrader
...
(venv)$ pylivetrader --help
(venv) Trevors-MacBook-Pro:pylivetrader tthackston$ pylivetrader --help
Usage: pylivetrader [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  run
  shell
  version
```

**Comment by CapitalZe** [comment]
Thanks for the advice. I had already tried as you suggested and the following is the output:

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6q3u7lr8/zipline/
`

Process:

- Macbook Pro

- Using VMWare Fusion

- Install Ubuntu 16.04

- Open and run it

- Install virtualenv and python 3.6, plus anything else like pip etc.

- create the venv with 3.6

- enter then venv and use pip to download and install pylivetrader

Then, depending on which protocol I follow, the outputs are always failures. One of the three failed outputs posted above:

1. 
`ERROR: Command errored out with exit status 1: /home/XXX/bin/python3 /home/dt-nicholas/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ge33c4yz/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython 'numpy==1.9.3; python_version=='"'"'3.5'"'"'' 'numpy==1.12.1; python_version=='"'"'3.6'"'"'' 'numpy==1.13.1; python_version>='"'"'3.7'"'"'' Check the logs for full command output.`

2. 
`ERROR: No matching distribution found for websockets>=8.0

`
3. 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6q3u7lr8/zipline/
`

Python version in venv:

`(venv) trial@ubuntu:~$ python --version
Python 3.6.8
`

I'm really at a loss, although it is most likely me overlooking something extremely simple.

**Comment by CapitalZe** [comment]
solution is [here](https://github.com/alpacahq/alpaca-trade-api-python/issues/112#event-2623513971).

Essentially, this solved it for me:

`sudo apt-get install python3.6-dev
`

**Comment by zhenyulin** [comment]
The solution here has worked for me.

But still curious about why failure happened when using python 3.6 from miniconda
