### ISSUE TITLE
smoke tests broken

### ISSUE THREAD

**Issue by vbandaru** [alpacahq/pylivetrader#119]
I am getting error with latest version of pylivetrader 0.1.0. 

Please also update documentation with working example of algo and corresponding smoke test.
`
$ python3 smoketest.py 
Traceback (most recent call last):
  File "smoketest.py", line 36, in <module>
    test_algo()
  File "smoketest.py", line 29, in test_algo
    pipeline_hook=pipeline2,
  File "/home/vijay/PycharmProjects/alpaca-rest-api-prototype/venv/lib/python3.6/site-packages/pylivetrader/testing/smoke/harness.py", line 61, in run_smoke
    a.pipeline_output = _pipeline_output
  File "/home/vijay/PycharmProjects/alpaca-rest-api-prototype/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 101, in __setattr__
    'an API method.'.format(name)
AttributeError: Cannot set pipeline_output on context object as it is the name of an API method.`

**Comment by Jbuxofplenty** [comment]
I also have this issue

**Comment by shlomikushchi** [comment]
I have fixed this issue in this commit. explination is inside
https://github.com/alpacahq/pylivetrader/commit/231516323c90e6e59fe865cf2d2b3654d227e40c
please let me know if something is still not working properly

**Comment by shlomikushchi** [comment]
this issue was resolved a bit differently (as initialy suggested by knoguchi) to avoid this issue: https://github.com/alpacahq/pylivetrader/issues/76

**Comment by spitzbubchen** [comment]
I also get this error when running the `smoke_pipelinelive.py`example:

```
> python smoke_pipelinelive.py 
> Traceback (most recent call last):
>   File "smoke_pipelinelive.py", line 19, in <module>
>     test_algo()
>   File "smoke_pipelinelive.py", line 10, in test_algo
>     pipeline_hook=pipe,
>   File "/home/rod/Projects/alpaca/venv/lib/python3.6/site-packages/pylivetrader/testing/smoke/harness.py", line 61, in run_smoke
>     a.pipeline_output = _pipeline_output
>   File "/home/rod/Projects/alpaca/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 101, in __setattr__
>     'an API method.'.format(name)
> AttributeError: Cannot set pipeline_output on context object as it is the name of an API method.
```
