### ISSUE TITLE
Examples never actually buy a stock

### ISSUE THREAD

**Issue by JayneFrack** [alpacahq/pylivetrader#131]
Hi, I have now had the MACD example running for multiple days but its never bought anything on my alpaca account.

**Comment by JayneFrack** [comment]
How would the code look to just simply buy a stock so that I can test if this would work?

**Comment by shlomikushchi** [comment]
you could do something like this (make sure you are using your paper account api keys so you could play with this):
change the code in `handle_data(context, data):` to
```
def handle_data(context, data):
    order_target(context.asset, 1)
```

this will make sure you buy 1 (and only 1) share of the asset you have defined in `initialize()` once the market is opened.

**Comment by shlomikushchi** [comment]
closing the issue. let us know if there are more problems with the example code
