### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. 

### ISSUE THREAD

**Issue by cunhafh** [alpacahq/pylivetrader#140]
I'm running a python script on PythonAnywhere and I'm accessing an API through an yaml config file. My bash command line is:

pylivetrader run-f bb.py --backend-config config.yaml
However this method calls the yaml.load function without specifying any arguments and this method is deprecated.

YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. 
I wonder how can I run this command on the bash in a safe way?

I appreciate the help guys!

Regards

**Comment by shlomikushchi** [comment]
@cunhafh fixed this. please pull from the master branch and let me know if it works fine

**Comment by shlomikushchi** [comment]
to install from github run this:
`pip install git+https://github.com/alpacahq/pylivetrader/`

**Comment by shlomikushchi** [comment]
by the way, the issue is when reading untrusted yaml files.
in this scenario - you read your own yaml file. so there is no security issue.
but the warning is now gone.

**Comment by cunhafh** [comment]
Hey!

Awesome, thank you so much!

**Comment by p595285902** [comment]
I am getting this error on the latest docker image.

**Comment by shlomikushchi** [comment]
Hi, we don't do `yaml.load` in the code base since v0.2.0 only `yaml.safe_load`

the dockerhub image is not maintained. if you downloaded from there that could be the issue. build the image yourself using the provided dockerfiles.
