### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by ikosenn** [alpacahq/pylivetrader#142]
Hi, @shlomikushchi 
I see you made a release yesterday. Are there place to get this to pypi?

**Comment by shlomikushchi** [comment]
we will do it shortly
in the meantime you can install it like this
`pip install git+https://github.com/alpacahq/pylivetrader`
this will install the latest master branch.
you could specify a specific tag if you want as well

**Comment by ikosenn** [comment]
Thank you!!! 

Kosen

**Comment by nabeelio** [comment]
Closed, but the version on pypi is still old

**Comment by nabeelio** [comment]
For anyone who is here looking how to pull the latest:

```
pipenv install "git+https://github.com/alpacahq/pylivetrader@v0.2.0#egg=pylivetrader"
```

**Comment by shlomikushchi** [comment]
you're right. re-opening the issue. 
will update it once we release the version to pypi.

**Comment by shlomikushchi** [comment]
current pypi version 0.3.0

**Comment by nabeelio** [comment]
Thanks!

**Comment by nabeelio** [comment]
@shlomikushchi are there any updates needed to https://github.com/alpacahq/pipeline-live for the Alpaca data, or is it just an interface to using this library?

**Comment by shlomikushchi** [comment]
it should work just the same since the api used did not change.
