### ISSUE TITLE
Update Pandas

### ISSUE THREAD

**Issue by nabeelio** [alpacahq/pylivetrader#145]
Is it possible to update to at least pandas 0.23.0? I need some of the DataFrame stuff added, particularly some additions to `from_dict()`. Pandas has been on > 1.0 for a while, there's some additions that would be useful

For example, this is a bug I'm running into which was fixed:
https://github.com/pandas-dev/pandas/issues/16766

There are a lot of bugs/issues with resample that have been fixed, which is important esp since there's a need to resample the minute-level data into different aggregates

**Comment by shlomikushchi** [comment]
so the zipline package requires pandas<=0.22.0
I tried upgrading to see if that works but it had issues. 
so for now, the pandas could not change.
I will try going a bit deeper and see if it's resolvable
(you could try upgrading locally and see if you can resolve those issues)

**Comment by nabeelio** [comment]
I've tried updating it, but no good. I guess an issue needs to be opened on zipline?

**Comment by nabeelio** [comment]
Does it use zipline or zipline-live? I can't tell... either way, that's gating pandas much further back too - https://github.com/zipline-live/zipline/blob/master/etc/requirements.txt#L20

**Comment by shlomikushchi** [comment]
we are not using zipline-live at the moment. 
zipline v1.3.0
