### ISSUE TITLE
macd_example.py

### ISSUE THREAD

**Issue by spitzbubchen** [alpacahq/pylivetrader#149]
For the example located at `pylivetrader/examples/MACD/macd_example.py` when pasting it in Quantopian I get the following error:

> Importing Logger from logbook raised an ImportError. No modules or attributes with a similar name were found. You tried to import a module that is not whitelisted on Quantopian. To see the list of allowed modules in the IDE, go to https://www.quantopian.com/docs/whitelists/ide-whitelist#algo-ide-whitelist. To see the list of additional modules allowed in Research, go to https://www.quantopian.com/docs/whitelists/research-whitelist#research-whitelist.

I would not say this is not a good example as the main goals of pylivetrader is:

> The main purpose is to run algorithms developed in the Quantopian platform in live trading via broker API.

**Comment by shlomikushchi** [comment]
the goal is to run quantopian algorithms in pylivetrader but not the other way around.
you cannot take code from pylivetrader and run it in Quantopian.

**Comment by spitzbubchen** [comment]
As I am new to Quantopian I didn't realize that `log` was one of these built in hidden Quantopian functions. May consider adding some additional comments to your example such as:

```
#
# Required Alpaca code
#
from pylivetrader.api import order_target, record, symbol
from logbook import Logger

log = Logger('macd-logger')

#
# Your Quantopian code
#
import pandas as pd

BUY_AMOUNT = 10

def initialize(context):
    # The initialize method is called at the very start of your script's
# etc...
```

One can now just paste in the code below "Your Quantopian code" into Quantopian and run it.

**Comment by shlomikushchi** [comment]
so, the goal of this project it not to help the user work with quantopian. it's for users that already use quantopian and are used to their workflow, to help them make an easy transition to the alpaca eco-system.

**Comment by spitzbubchen** [comment]
Okay, fair enough. I'll close the issue.
