### ISSUE TITLE
Q translater

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/pylivetrader#15]
Having the Quantopian migration step in documentation is great, but many of the processes can be automated. There is a partial code that tries to translate the import paths, but this breaks the mapping from the original code when it runs, and the better way to do it is to provide another step (CLI) to explicitly translate the source code.

**Comment by shlomikushchi** [comment]
added in this commit: https://github.com/alpacahq/pylivetrader/commit/5649d53afdb135fd62d12427cd12e4cb57fa617f
