### ISSUE TITLE
How to backtest

### ISSUE THREAD

**Issue by spitzbubchen** [alpacahq/pylivetrader#151]
I am wondering if it is possible to run a backtest on my pylivetrader algorithm in a similar way as with zipline (i.e. pylivetrader run -f algos/algo.py --start 2014-1-1 --end 2018-1-1 -o dma.pickle) using the Polygon API instead of Quantl? I would like to confirm that it produces the same result as in Quantopian.

**Comment by shlomikushchi** [comment]
currently we do not have a way to backtest in pylivetrader
there's the smoke tool that allows you to simulate the workflow, but it's using mocked data and the goal is to make sure you don't have syntax errors

**Comment by spitzbubchen** [comment]
So I guess the only option is to use the Alpaca paper account?

**Comment by shlomikushchi** [comment]
you could backtest in zipline and then paper trade with pylivetrader. but basically yes - with pylivetrader you could paper trade or live trade
