### ISSUE TITLE
Unauthorized User: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by jmaslek** [alpacahq/pylivetrader#153]
I am having an issue similiar to #68.

I am using the exact code sample for the [simple usage](https://github.com/alpacahq/pylivetrader#simple-usage).

I have gone into the polygon rest.py and changed the url to:
```
def _request(self, method, path, params=None, version='v1'):
        url = 'https://data.alpaca.markets/v1' + path
```
I have tried this with both v1 and v2.  The error message says:
`
[2020-05-12 13:48:00.949482] ERROR: Executor: 401 Client Error: Unauthorized for url: https://data.alpaca.markets/v1/aggs/ticker/AAPL/range/1/minute/1589279220000/1589291280000?unadjusted=False&apiKey=PKC6MPB8R8KMQX2D3UR9

`My env variables are:
```
$ export APCA_API_KEY_ID=PKC6MPB8R8KMQX2D3UR9
$ export APCA_API_SECRET_KEY=xuju3RxFwRfJy37t7QW9cQQN9IENDbjISecDuWOE
$ export APCA_API_BASE_URL=https://paper-api.alpaca.markets
$ pylivetrader run -f algo.py
```

**Comment by shlomikushchi** [comment]
do you have a funded account? this version only works for a funded account.
in the next version you will be able to use the package with a non funded account

**Comment by jmaslek** [comment]
So this is for the paper trading.  I am currently waiting on being approved for live trading.

**Comment by shlomikushchi** [comment]
the paper trading needs data as well. data is only available on funded account. 
but this will change in the next version that will be released soon

**Comment by jmaslek** [comment]
I see.  So what data can be used for paper trading?
