### ISSUE TITLE
Pickle error with pipeline-live Factor

### ISSUE THREAD

**Issue by jmaslek** [alpacahq/pylivetrader#154]
I am running into an issue very similar to #78, just with an alpaca factor I am running the following:

```
from pipeline_live.engine import LivePipelineEngine
from pipeline_live.data.sources.alpaca import list_symbols
from pipeline_live.data.alpaca.pricing import USEquityPricing
from pipeline_live.data.polygon.fundamentals import PolygonCompany
from pipeline_live.data.alpaca.factors import AverageDollarVolume
from zipline.pipeline import Pipeline


def initialize(context):
    eng = LivePipelineEngine(list_symbols)
    top5 = AverageDollarVolume(window_length=20).top(5)
    pipe = Pipeline({
        'close': USEquityPricing.close.latest,
        'marketcap': PolygonCompany.marketcap.latest,
    }, screen=top5)
    context.pipe = pipe
```
When I run this, I get an error in the StateStore init : 

```

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/statestore/__init__.py", line 99, in save
    self.storage_engine.save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/statestore/__init__.py", line 35, in save
    pickle.dump(state, f)
_pickle.PicklingError: Can't pickle <class 'abc.AverageDollarVolume'>: attribute lookup AverageDollarVolume on abc failed
```

I have tried uninstalling and reinstalling all of: pylivetrader, pipeline-live,zipline and alpaca-trade-api.  I have entered the env variables for a funded account.

**Comment by shlomikushchi** [comment]
I just executed your exact example and it works for me. 
do a pip freeze and let's the versions of all packages.. maybe something is different than my setup.

**Comment by jmaslek** [comment]
Python version 3.6.3
```
aiohttp==3.6.2
alembic==1.4.2
alpaca-trade-api==0.48
alpha-vantage==2.2.0
appnope==0.1.0
astor==0.8.1
async-timeout==3.0.1
asyncio-nats-client==0.10.0
attrs==19.3.0
backcall==0.1.0
bcolz==0.12.1
Bottleneck==1.0.0
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
contextlib2==0.6.0.post1
cyordereddict==1.0.0
Cython==0.29.17
decorator==4.4.2
Deprecated==1.2.10
empyrical==0.5.3
idna==2.9
idna-ssl==1.1.0
iexfinance==0.4.3
intervaltree==3.0.2
ipython==7.14.0
ipython-genutils==0.2.0
jedi==0.17.0
Logbook==1.5.3
lru-dict==1.1.6
lxml==4.5.0
Mako==1.1.2
MarkupSafe==1.1.1
multidict==4.7.6
multipledispatch==0.6.0
networkx==1.11
numexpr==2.7.1
numpy==1.18.4
pandas==0.22.0
pandas-datareader==0.8.1
parso==0.7.0
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
pipeline-live==0.1.9
prompt-toolkit==3.0.5
ptyprocess==0.6.0
Pygments==2.6.1
pylivetrader==0.1.1
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
requests-file==1.5.1
scipy==1.4.1
six==1.14.0
sortedcontainers==2.1.0
SQLAlchemy==1.3.17
statsmodels==0.11.1
tables==3.6.1
toolz==0.10.0
trading-calendars==1.11.7
traitlets==4.3.3
typing-extensions==3.7.4.2
urllib3==1.24.3
wcwidth==0.1.9
websocket-client==0.57.0
websockets==8.1
wrapt==1.12.1
yarl==1.4.2
zipline==1.3.0

```

**Comment by shlomikushchi** [comment]
it seems you are running with an old version of pylivetrader. 
install v0.3.0 and try again.

**Comment by jmaslek** [comment]
I just ran pip install pylivetrader==0.3.0 and I get the same error

**Comment by jmaslek** [comment]
Not sure if this helps at all, but if I run pylivetrader shell 

```

Traceback (most recent call last):
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/bin/pylivetrader", line 10, in <module>
    sys.exit(main())
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Jamie/PycharmProjects/LiveTrading/venv/lib/python3.6/site-packages/pylivetrader/__main__.py", line 230, in shell
    ctx = process_algo_params(ctx, **kwargs)
TypeError: process_algo_params() missing 7 required positional arguments: 'data_frequency', 'statefile', 'retry', 'log_level', 'timezone', 'storage_engine', and 'quantopian_compatible'

```

**Comment by shlomikushchi** [comment]
> Not sure if this helps at all, but if I run pylivetrader shell
> 
so that's actually a different bug. (thanks for reporting it)
it is fixed in the main branch and you could install it with: 
`pip install git+https://github.com/alpacahq/pylivetrader -U`

it is not related to the pickle issue. 
when you run the sample code, do you still get a pickling issue?

**Comment by jmaslek** [comment]
Yes, I am getting the Pickling error with the pylivetrader at 0.3.0.

**Comment by shlomikushchi** [comment]
in order to fix your issue I need a way to reproduce it locally.
and it works fine locally..
- try a fresh install(completely new with a new virtual env) and then try to run the sample code from the repo
- post the sample code you run, and I will try to run the exact code locally.

**Comment by jmaslek** [comment]
So I started a fresh venv and ran pip install pylivetrader==0.3.0.  The result was an error:

`Failed to build bottleneck lru-dict cyordereddict bcolz
ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly
`

Running on pip 20.1  Im guessing something wasn't installing correctly.

**Comment by shlomikushchi** [comment]
what OS are you running on?

**Comment by jmaslek** [comment]
MacOS Mojave Version 10.14.6

**Comment by shlomikushchi** [comment]
so bottleneck is required by zipline and it should be greater than 1.0.0. install it manually with a version that could be satisfied for your env. then install pylivetrader
let me know which version you install so I will make sure it runs correctly here too

**Comment by jmaslek** [comment]
I have no idea what I did, but it is not having that pickling error when I run from my terminal.  I have something weird in my paths....  my pylivetrader and associated are in my python 3.6 frameworks in library.  I cannot run pip install or else I get the cannot use PEP 516 for a couple packages, and I cannot run from the pycharm terminal.  

I believe what made it work was that when I did pip install pylivetrader==0.3.0, it didn't update the pylivetrader in my frameworks, so manually doing that fixed it.

Do you have any reccomendations for cleaning that up?  I will close the issue since it is on my end.

**Comment by shlomikushchi** [comment]
do pip uninstall to all packages. and only work inside a virtualenv. will save you a lot of trouble in the future
