### ISSUE TITLE
How to determine number of trading days since purchase

### ISSUE THREAD

**Issue by spitzbubchen** [alpacahq/pylivetrader#158]
Using pylivetrader I can access the stock purchase date as follows:

```
for stock in context.portfolio.positions:
        print(stock.symbol, context.portfolio.positions[stock].last_sale_date)
```

Does pylivetrader have a built in method to determine the number of trading days since a purchase or is it necessary to import the alpaca trade API? For example:

```
import alpaca_trade_api as tradeapi

api = tradeapi.REST()

# Check when the market was open on Dec. 1, 2018
date = '2018-12-01'
calendar = api.get_calendar(start=date, end=date)[0]
print('The market opened at {} and closed at {} on {}.'.format(
    calendar.open,
    calendar.close,
    date
))
```

**Comment by shlomikushchi** [comment]
I'm not sure I understand what you are trying to do here...
you get purchase date by using: `last_sale_date`?
now what are you trying to do?
the second part of your example has no positions in it....

**Comment by spitzbubchen** [comment]
I would like to liquidate stocks after a certain number of days. In quantopian people seem to track this by putting it in the initialization context [](https://www.quantopian.com/posts/selling-stock-after-time). However, this does not work well in pylivetrader when the algorithm as restarting the algo will sets the count down timer back to zero.

Would something like this work?

```
import alpaca_trade_api as tradeapi
api = tradeapi.REST()
def days_since_purchase(context, stock):
    purchased = context.portfolio.positions[stock].last_sale_date.date()
    today = datetime.strftime(datetime.now(), '%Y-%m-%d')
    days = api.get_calendar(start = purchased, end = today)
    return len(days)
```

**Comment by shlomikushchi** [comment]
you could do today - purchased. that would be much simpler.. unles you want to only count open market days, then your solution seems correct.
e.g

![image](https://user-images.githubusercontent.com/7924802/83439270-7fb08a00-a44b-11ea-9e99-5b6a04d15512.png)

we don't get the weekend days (saturday, sunday) in the response

**Comment by spitzbubchen** [comment]
Thanks! I now have the number of trade days sorted out. However, I am now confused by what does `context.portfolio.positions[stock].last_sale_date.date()` mean? It doesn't seem to be the date when I first enter a position. Also, I don't see how this info is obtained on the Alpaca API:

```
api = tradeapi.REST()
portfolio = api.list_positions()
for position in portfolio:
    print(position)
```

> Position({   'asset_class': 'us_equity',
>     'asset_id': '1ac8b6c7-e336-4063-8c8a-d8ea1fa67d00',
>     'avg_entry_price': '0.79552',
>     'change_today': '0.0054040467512882',
>     'cost_basis': '3.9776',
>     'current_price': '0.8',
>     'exchange': 'AMEX',
>     'lastday_price': '0.7957',
>     'market_value': '4',
>     'qty': '5',
>     'side': 'long',
>     'symbol': 'LBY',
>     'unrealized_intraday_pl': '0.0215',
>     'unrealized_intraday_plpc': '0.0054040467512882',
>     'unrealized_pl': '0.0224',
>     'unrealized_plpc': '0.0056315366049879'})

**Comment by shlomikushchi** [comment]
you should store it in your context object. it is not deleted next time you restart the app
another option you have is to use redis (check the readme)
