### ISSUE TITLE
Any plans to write documentation on how to migrate from 'optimize' to alpaca's equivalent?

### ISSUE THREAD

**Issue by sradu** [alpacahq/pylivetrader#166]
I went through this https://alpaca.markets/docs/alpaca-works-with/quantopian-to-pipeline-live/ but I think it would save people a lot of time. I'm seeing this question on the Quantopiam forum as well:

<img width="1023" alt="Screen Shot 2020-06-23 at 9 03 54 PM" src="https://user-images.githubusercontent.com/82214/85498726-1a0c7500-b595-11ea-80d9-2fc6bdcf7dab.png">

**Comment by shlomikushchi** [comment]
Hi, 
we currently only support the open source zipline api
the optimize api is not opened source so we don't support it

**Comment by sradu** [comment]
I noticed it wasn't open source. What I'd love is a tutorial on how to migrate from 'optimize' code to Alpaca's equivalent, if that makes sense.

**Comment by shlomikushchi** [comment]
since it is not open we are not supporting this currently.
implementing it will result in completely different results than on Quantopian since the internals will be completely different

**Comment by sradu** [comment]
Understood!
