### ISSUE TITLE
DataPortal._get_realtime_bars

### ISSUE THREAD

**Issue by weiguang-zz** [alpacahq/pylivetrader#180]
why the param:end_dt is dropped?

https://github.com/alpacahq/pylivetrader/blob/8a339ab235152717158fcc5bfc6bd98ea4a6d7ab/pylivetrader/data/data_portal.py#L29

**Comment by weiguang-zz** [comment]
Not passed to self.backend.get_bars

**Comment by shlomikushchi** [comment]
Hi @weiguang-zz 
pylivetrader is a live trading package. so end_dt is always now.
that is why it is not used.
you cannot backtest with this package.

**Comment by weiguang-zz** [comment]
In my opinion， the end_dt should be generated by the RealTimeClock.

**Comment by shlomikushchi** [comment]
what do you mean? why should it be generated by the clock?

**Comment by weiguang-zz** [comment]
forgot about the clock, I did not express clearly.

the reason is: If you don't pass end_dt to the method:get_bars,  you should generated by yourself, the logic is not simply get the current time.  the logic should be: Determine whether the current time is trading time. If yes, take the minute of the current time. If not, just take the minute of the last transaction time.  

you can check the current logic of  generation start time and end time, it is very time consuming.
https://github.com/alpacahq/pylivetrader/blob/c07f0079c425b0e2defdd905ffc39d097ba623ee/pylivetrader/backend/alpaca.py#L566
