### ISSUE TITLE
Zipline v1.4.0 support

### ISSUE THREAD

**Issue by bwees** [alpacahq/pylivetrader#182]
Are there plans for support of zipline 1.4.0? I am using 1.4.0 and there are some conflicts with pip and was wondering if there will be issues if I use 1.4.0 with pylivetrader.

**Comment by shlomikushchi** [comment]
Hi,
it's in the backlog but it will take some time
in the meantime you could have 2 virtual envs to use both.
the algo logic hasn't changed

**Comment by bwees** [comment]
Ok thank you.
