### ISSUE TITLE
Unable to activate Polygon data

### ISSUE THREAD

**Issue by granthooks** [alpacahq/pylivetrader#183]
Backend always uses 'alpaca' even when flag is set to true.
```
$ cat config.yaml
key_id: xxxxxxx
secret: yyyyyyyyy
base_url: https://paper-api.alpaca.markets
use_polygon: true
```
When algo is run with
`pylivetrader run -f algo.py --backend-config config.yaml `
output:
`Algorithm: livetrader start running with backend = alpaca data-frequency = minute`

Also tried specifying --backend option with:
`pylivetrader run -f algo.py --backend polygon --backend-config config.yaml `
output:
`RuntimeError: Could not find backend package `polygon`.`

Is this because a polygon.py file is missing from \pylivetrader-master\pylivetrader\backend\ ?

**Comment by shlomikushchi** [comment]
Hi, the backend is always alpaca. the data source is determined by the `use_polygon` param in the config file which you had set correctly.
