### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by bwees** [alpacahq/pylivetrader#196]
Hello, I am working on using pylivetrader on ARM with a Raspberry Pi. In doing so, I discovered that I need to compile Pandas from source if I were to use Python 3.6. Has anyone used 3.7 with success with pylivetrader (I know that pylivetrader only support 3.6 but was wondering if there was success with 3.7)? I am also wondering if Pandas 0.23 works as well.

Thanks for your help in advanced.

**Comment by shlomikushchi** [comment]
Hi, so the limitation comes from the package zipline.
now, the thing is that we use zipline mainly for the interface definitions and the engine is implemented by this package.
so, my intuition says this may work as you hope it would, but this needs to be checked
