### ISSUE TITLE
End of Day function

### ISSUE THREAD

**Issue by bwees** [alpacahq/pylivetrader#198]
Is there a function I can define that will run at the end of the day? I am trying to liquidate all of the stocks I own at the end of the day right before the day is over. This is because pylivetrader does not run after hours so, I would like to liquidate what I have. Is there a better way to do this with different orders or by other means?

**Comment by shlomikushchi** [comment]
you could use `schedule_function` 

`schedule_function(rebalance, date_rules.every_day(), time_rules.market_close(minutes=10))`
but it's only during market hours.

if you want to do something after market hours, you could edit the events code in `RealtimeClock`

**Comment by bwees** [comment]
Ok thank you so much!

Brandon Wees

**Comment by bwees** [comment]
Is the ```time_rules.market_close(minutes=10)``` to minutes before the market closes?

**Comment by shlomikushchi** [comment]
10 minutes before market close yes
