### ISSUE TITLE
AttributeError: type object 'USEquityPricing' has no attribute 'get_loader'

### ISSUE THREAD

**Issue by Nicosunaa** [alpacahq/pylivetrader#199]

**Comment by Nicosunaa** [comment]
[2020-10-05 15:47:09.990365] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
ERROR:root:error while consuming ws messages: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
Traceback (most recent call last):

**Comment by Nicosunaa** [comment]
Hi! I trying to run an algorithm with pylivetrader command ($pylivetrader run -f algo.py) but I continue getting the same error: 

[2020-10-05 15:47:09.990365] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
ERROR:root:error while consuming ws messages: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

**Comment by shlomikushchi** [comment]
Hi, what is the USEquityPricing object you are using?
send the import line

also check this example code which uses the pipeline-live. that may help you:
https://github.com/alpacahq/pylivetrader/blob/master/examples/using_pipeline_live/pipeline_live_example.py

**Comment by Nicosunaa** [comment]
I'm importing USEquityPricing using: from pipeline_live.data.alpaca.pricing import USEquityPricing
The problem was with factors I was using . Thanks for the example
