### ISSUE TITLE
Stop loss logic

### ISSUE THREAD

**Issue by bwees** [alpacahq/pylivetrader#202]
I have been experimenting with stop-loss orders and had a question. Then you pass the price to the order function, is that price per share or for the entire order? For example, if I had 100 shares of Apple for $100, would I pass $95 to the function (5% loss) or, would I pass $9500 (also a 5% loss)?

**Comment by shlomikushchi** [comment]
per share

**Comment by bwees** [comment]
Okay thank you

Brandon Wees
