### ISSUE TITLE
Add oauth param in the tradeapi.REST()

### ISSUE THREAD

**Issue by firobeid** [alpacahq/pylivetrader#208]
Can you please add the authentication token parameter to the tradeapi.REST() whenever it is called in the backend of the pylivetrader or its dependencies so that bearer tokems can be passed for authenticate developers routed users api calls?

**Comment by shlomikushchi** [comment]
Hi,
as I mentioned in your other post, the Stream service does not support oauth currently. so even we could add oauth to the REST service, the Stream service will not work with oauth, which mean you cannot get trade and account updates.
