### ISSUE TITLE
pylivetrader needs update for v2 bars 

### ISSUE THREAD

**Issue by Moccazio** [alpacahq/pylivetrader#254]
pylivetrader and pipeline-live need an update for v2 bars. When I run pylivetrader i am getting an client error while using v1 bars.

**Comment by drew887** [comment]
Hey @Moccazio sorry about this one. I recently pushed a new release `0.7.0` for pylivetrader if possible can you please test with that version and let me know if it fixes it? 

Also for the pipeline-live part can you please open a [ticket in its own repo](https://github.com/alpacahq/pipeline-live) separately for issues it has?

**Comment by Moccazio** [comment]
Hello @drew887 thx for working on the bug. I just updated pylivetrader to 0.7.0 and till now it looks fine. I will look into the test algo I just launched and after the next run of pylivetrader when the market opens I will give you feedback if it still shows an error.

**Comment by Moccazio** [comment]
@drew887 So the update didnt fix anything, cause the v1 bars are still used to get the data from pipeline-live. You need to fix the pipeline-live data source to fix pylivetrader. Here is the error-code, maybe it helps you for fixing the package.

`Traceback (most recent call last):
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/bin/pylivetrader", line 8, in <module>
Apr  4 12:45:17     sys.exit(main())
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
Apr  4 12:45:17     return self.main(*args, **kwargs)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1062, in main
Apr  4 12:45:17     rv = self.invoke(ctx)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
Apr  4 12:45:17     return _process_result(sub_ctx.command.invoke(sub_ctx))
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
Apr  4 12:45:17     return ctx.invoke(self.callback, **ctx.params)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 763, in invoke
Apr  4 12:45:17     return __callback(*args, **kwargs)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
Apr  4 12:45:17     return f(get_current_context(), *args, **kwargs)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/__main__.py", line 277, in run
Apr  4 12:45:17     algorithm.run(retry=ctx.retry)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 275, in run
Apr  4 12:45:17     return self.executor.run(retry=retry)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 119, in run
Apr  4 12:45:17     algo.before_trading_start(self.current_data)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 248, in before_trading_start
Apr  4 12:45:17     self._before_trading_start(self, data)
Apr  4 12:45:17   File "ml_model_algo.py", line 225, in before_trading_start
Apr  4 12:45:17     output = context.pipeline_output('ml_model')
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 1095, in pipeline_output
Apr  4 12:45:17     output = eng.run_pipeline(self._pipelines[name])
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/engine.py", line 77, in run_pipeline
Apr  4 12:45:17     initial_workspace,
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/engine.py", line 244, in compute_chunk
Apr  4 12:45:17     to_load, mask_dates, symbols, mask,
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/alpaca/pricing_loader.py", line 42, in load_adjusted_array
Apr  4 12:45:17     prices = alpaca.get_stockprices(chart_range)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 19, in get_stockprices
Apr  4 12:45:17     return get_stockprices_cached(all_symbols)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/util.py", line 68, in wrapper
Apr  4 12:45:17     body = func(*args, **kwargs)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 17, in get_stockprices_cached
Apr  4 12:45:17     return _get_stockprices(all_symbols, limit, timespan)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 40, in _get_stockprices
Apr  4 12:45:17     return parallelize(fetch, splitlen=199)(symbols)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/util.py", line 30, in wrapper
Apr  4 12:45:17     task_result = task.result()
Apr  4 12:45:17   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
Apr  4 12:45:17     return self.__get_result()
Apr  4 12:45:17   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
Apr  4 12:45:17     raise self._exception
Apr  4 12:45:17   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Apr  4 12:45:17     result = self.fn(*self.args, **self.kwargs)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 30, in fetch
Apr  4 12:45:17     barset = api.get_barset(symbols, timespan, limit)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/deprecation.py", line 260, in _inner
Apr  4 12:45:17     return function(*args, **kwargs)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 578, in get_barset
Apr  4 12:45:17     resp = self.data_get('/bars/{}'.format(timeframe), params)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 256, in data_get
Apr  4 12:45:17     'GET', path, data, base_url=base_url, api_version=api_version,
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 202, in _request
Apr  4 12:45:17     return self._one_request(method, url, opts, retry)
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 223, in _one_request
Apr  4 12:45:17     resp.raise_for_status()
Apr  4 12:45:17   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
Apr  4 12:45:17     raise HTTPError(http_error_msg, response=self)
Apr  4 12:45:17 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://data.alpaca.markets/v1/bars/day?symbols=BIB%2CPTPI%2CCLRO%2CXSMO%2CCLS%2CCLSA%2CCLSC%2CCLSD%2CCLSE%2CPTR%2CCLVT%2CCMC%2CCMCA%2CCMCAU%2CCMCL%2CBICK%2CPTRA%2CBIDS%2CBIDU%2CBIF%2CBIG%2CBIGC%2CPTRB%2CBIGY%2CBIGZ%2CBIIB%2CBIL%2CXSOE%2CBILI%2CBILL%2CBILS%2CXSPA%2CBIMI%2CCBON%2CBIO%2CBIO.B%2CPTRS%2CEJAN%2CBIOL%2CPTSI%2CBIOS%2CBIOSU%2CBIOT%2CBIOTU%2CCBIO%2CCMCM%2CCMCO%2CCMCSA%2CCMCT%2CCMCTP%2CXTJA%2CXTJL%2CXTLB%2CCMDY%2CCME%2CXTN%2CCMF%2CCMG%2CXTNT%2CPTVE%2CBIOX%2CBIP%2CBIPC%2CBIPH%2CBIPI%2CBIVI%2CBIZD%2CBJ%2CBJAN%2CXTOC%2CSVA%2CEJFA%2CACES%2CPTY%2CAFB%2CEL%2CCMI%2CCBH%2CELEV%2CPUBM%2CCMLS%2CCMMB%2CCMP%2CELF%2CPUCK%2CCMPGY%2CCMPR%2CCMPS%2CPUCKU%2CCMPX%2CARTL%2CCMRE%2CCMRX%2CARTEU%2CCMS%2CARTE%2CCMSA%2CCMSC%2CCMSD%2CCMT%2CBKEM%2CBKEP%2CBKEPP%2CBKES%2CBKF%2CPUI%2CPUK%2CBKH%2CBKHY%2CBKI%2CBKIE%2CBKIS%2CARRY%2CPULM%2CPULS%2CBKKT%2CELOX%2CBKLC%2CPUMP%2CBKLN%2CBKMC%2CBKN%2CBKNG%2CXYLG%2CARRWU%2CBKR%2CBKSB%2CBKSC%2CPUNK%2CBKSE%2CBKSY%2CBKT%2CBKTI%2CBKU%2CELP%2CCMTG%2CCMTL%2CCMU%2CBAMR%2CBAMI%2CBKUI%2CBKUS%2CBKYI%2CY%2CBL%2CBLCT%2CBLD%2CBLDE%2CBLDG%2CBLDP%2CBLDR%2CBLE%2CBAMH%2CBLES%2CBLEU%2CBLEUU%2CELQD%2CBLFS%2CBLFY%2CARRW%2CARR%2CSOXL%2CPUTW%2CYALA%2CCNCR%2CPUYI%2CCND%2CCND.U%2CCNDA%2CCNDA.U%2CCNDB%2CCNTB%2CPV%2CCNTG%2CPV.U%2CPVAL%2CVHC%2CPVBC%2CVHI%2CBLHY%2CBLI%2CABM%2CBLIN%2CBLK%2CBLKB%2CBLKC%2CBAM%2CBLL%2CYANG%2CYARIY%2CPVI%2CPVL%2CBALY%2CBLMN%2CBLNG%2CBLNGU%2CBLNK%2CBALT%2CBLOK&limit=369`

**Comment by drew887** [comment]
Hey @Moccazio sorry for the week long gap here, but we just pushed `0.7.1` which hopefully fixes the issues we were seeing with pipeline-live. IIf possible can you please test with that version and let me know if it fixes it? :pray:

**Comment by Moccazio** [comment]
Hey @drew887 no worries I had a short holiday too. I ran the test algo and after todays market open I can tell you more.

**Comment by Moccazio** [comment]
@drew887 it seems like getting data is working now for a simple algorithm but sklearn throws an error on ml model. It used to work just fine. 

` /home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1665: RuntimeWarning: Degrees of freedom <= 0 for slice.
Apr 13 20:01:20   keepdims=keepdims)
Apr 13 20:01:20 <string>:68: RuntimeWarning: Mean of empty slice
Apr 13 20:01:20 <string>:69: RuntimeWarning: invalid value encountered in true_divide
Apr 13 20:01:20 Traceback (most recent call last):
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/bin/pylivetrader", line 8, in <module>
Apr 13 20:01:20     sys.exit(main())
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
Apr 13 20:01:20     return self.main(*args, **kwargs)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1062, in main
Apr 13 20:01:20     rv = self.invoke(ctx)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
Apr 13 20:01:20     return _process_result(sub_ctx.command.invoke(sub_ctx))
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
Apr 13 20:01:20     return ctx.invoke(self.callback, **ctx.params)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 763, in invoke
Apr 13 20:01:20     return __callback(*args, **kwargs)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
Apr 13 20:01:20     return f(get_current_context(), *args, **kwargs)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/__main__.py", line 277, in run
Apr 13 20:01:20     algorithm.run(retry=ctx.retry)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 275, in run
Apr 13 20:01:20     return self.executor.run(retry=retry)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 119, in run
Apr 13 20:01:20     algo.before_trading_start(self.current_data)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 248, in before_trading_start
Apr 13 20:01:20     self._before_trading_start(self, data)
Apr 13 20:01:20   File "ml_model_algo.py", line 225, in before_trading_start
Apr 13 20:01:20     output = context.pipeline_output('ml_model')
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 1095, in pipeline_output
Apr 13 20:01:20     output = eng.run_pipeline(self._pipelines[name])
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/engine.py", line 77, in run_pipeline
Apr 13 20:01:20     initial_workspace,
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/engine.py", line 252, in compute_chunk
Apr 13 20:01:20     mask,
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/zipline/pipeline/mixins.py", line 214, in _compute
Apr 13 20:01:20     compute(date, masked_assets, out_row, *inputs, **params)
Apr 13 20:01:20   File "ml_model_algo.py", line 137, in compute
Apr 13 20:01:20     self._maybe_train_model(today, returns, inputs)
Apr 13 20:01:20   File "ml_model_algo.py", line 135, in _maybe_train_model
Apr 13 20:01:20     self._train_model(today, returns, inputs)
Apr 13 20:01:20   File "ml_model_algo.py", line 128, in _train_model
Apr 13 20:01:20     features = scaler.fit_transform(features)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/sklearn/base.py", line 699, in fit_transform
Apr 13 20:01:20     return self.fit(X, **fit_params).transform(X)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/sklearn/preprocessing/_data.py", line 730, in fit
Apr 13 20:01:20     return self.partial_fit(X, y, sample_weight)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/sklearn/preprocessing/_data.py", line 768, in partial_fit
Apr 13 20:01:20     force_all_finite='allow-nan', reset=first_call)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/sklearn/base.py", line 421, in _validate_data
Apr 13 20:01:20     X = check_array(X, **check_params)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
Apr 13 20:01:20     return f(*args, **kwargs)
Apr 13 20:01:20   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/sklearn/utils/validation.py", line 729, in check_array
Apr 13 20:01:20     context))
Apr 13 20:01:20 ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required by StandardScaler.
Apr 13 20:02:06 [2022-04-13 20:02:06.510880] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Apr 13 20:02:14 [2022-04-13 20:02:14.132437] INFO: builtins: initialize
Apr 13 20:02:14 [2022-04-13 20:02:14.162403] INFO: builtins: before_trading_start
Apr 13 20:02:14 [2022-04-13 20:02:14.407041] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=758
Apr 13 20:09:39 [2022-04-13 20:09:39.635056] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=497
Apr 13 20:18:24 [2022-04-13 20:18:24.557699] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=366`

**Comment by Moccazio** [comment]
@drew887 The bug is fixe and pylivetrader & pipeline-live are working again thx for your help!!!

**Comment by drew887** [comment]
Awesome! Thank you for taking the time to test and having patience while we worked through these issues :tada:
