### ISSUE TITLE
connection error while running pylivetrader 

### ISSUE THREAD

**Issue by Moccazio** [alpacahq/pylivetrader#256]
So while running pylivetrader urlib3 suddendly throws connection error. 

`2022-04-29 13:47:01 - Task preparing to start
Apr 29 13:50:40 [2022-04-29 13:50:40.918040] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Apr 29 13:50:46 Traceback (most recent call last):
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
Apr 29 13:50:46     (self._dns_host, self.port), self.timeout, **extra_kw
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/util/connection.py", line 72, in create_connection
Apr 29 13:50:46     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Apr 29 13:50:46   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
Apr 29 13:50:46     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Apr 29 13:50:46 socket.gaierror: [Errno -3] Temporary failure in name resolution
Apr 29 13:50:46 During handling of the above exception, another exception occurred:
Apr 29 13:50:46 Traceback (most recent call last):
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
Apr 29 13:50:46     chunked=chunked,
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
Apr 29 13:50:46     self._validate_conn(conn)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
Apr 29 13:50:46     conn.connect()
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
Apr 29 13:50:46     self.sock = conn = self._new_conn()
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
Apr 29 13:50:46     self, "Failed to establish a new connection: %s" % e
Apr 29 13:50:46 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3bd8fd5b70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
Apr 29 13:50:46 During handling of the above exception, another exception occurred:
Apr 29 13:50:46 Traceback (most recent call last):
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
Apr 29 13:50:46     timeout=timeout
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
Apr 29 13:50:46     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
Apr 29 13:50:46     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Apr 29 13:50:46 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.alpaca.markets', port=443): Max retries exceeded with url: /v2/assets?asset_class=us_equity (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3bd8fd5b70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Apr 29 13:50:46 During handling of the above exception, another exception occurred:
Apr 29 13:50:46 Traceback (most recent call last):
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/bin/pylivetrader", line 8, in <module>
Apr 29 13:50:46     sys.exit(main())
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
Apr 29 13:50:46     return self.main(*args, **kwargs)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/click/core.py", line 1062, in main
Apr 29 13:50:46     rv = self.invoke(ctx)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
Apr 29 13:50:46     return _process_result(sub_ctx.command.invoke(sub_ctx))
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
Apr 29 13:50:46     return ctx.invoke(self.callback, **ctx.params)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/click/core.py", line 763, in invoke
Apr 29 13:50:46     return __callback(*args, **kwargs)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
Apr 29 13:50:46     return f(get_current_context(), *args, **kwargs)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/pylivetrader/__main__.py", line 277, in run
Apr 29 13:50:46     algorithm.run(retry=ctx.retry)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 265, in run
Apr 29 13:50:46     self.asset_finder.retrieve_all(self.asset_finder.sids)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/pylivetrader/assets/finder.py", line 192, in sids
Apr 29 13:50:46     for sid, _ in self._asset_cache.items()
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/pylivetrader/assets/finder.py", line 38, in _asset_cache
Apr 29 13:50:46     for asset in self.backend.get_equities()
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 190, in get_equities
Apr 29 13:50:46     raw_assets = self._api.list_assets(asset_class='us_equity')
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 522, in list_assets
Apr 29 13:50:46     resp = self.get('/assets', params)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 239, in get
Apr 29 13:50:46     return self._request('GET', path, data)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 202, in _request
Apr 29 13:50:46     return self._one_request(method, url, opts, retry)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 221, in _one_request
Apr 29 13:50:46     resp = self._session.request(method, url, **opts)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
Apr 29 13:50:46     resp = self.send(prep, **send_kwargs)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
Apr 29 13:50:46     r = adapter.send(request, **kwargs)
Apr 29 13:50:46   File "/home/Moccazio/.virtualenvs/ziplive/lib/python3.6/site-packages/requests/adapters.py", line 519, in send
Apr 29 13:50:46     raise ConnectionError(e, request=request)
Apr 29 13:50:46 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.alpaca.markets', port=443): Max retries exceeded with url: /v2/assets?asset_class=us_equity (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3bd8fd5b70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))`

**Comment by Moccazio** [comment]
@drew887 so it used to work but today pylivetrader throws that error while runnning.

**Comment by drew887** [comment]
Hmm as always with a case of DNS failure, I have to ask did you try it on another machine/network/dns provider? We definitely haven't pushed any changes to pylive since the last round of fixes :thinking:. 

On the machine this error occurred on can you please run a dns lookup to see if its the problem? :thinking:

**Comment by Moccazio** [comment]
@drew887 ok, seems that you are right. The issue is at dns failure not pylivetrader.
