### ISSUE TITLE
fyi - Supported platforms in readme should specify python3

### ISSUE THREAD

**Issue by johndpope** [alpacahq/pylivetrader#26]
I'm dinking around with swift + python and it only works with python2.

otherwise - I hit this error.
https://github.com/nats-io/asyncio-nats

**Should be compatible with at least Python +3.5.1 using gnatsd as the server.**

(gymai) ➜  ~ pip install asyncio-nats-client
Collecting asyncio-nats-client
  Using cached https://files.pythonhosted.org/packages/f6/a0/3e9a55cfe262699a2ce98714e14a7381bc674112f567af80457d16ea9b2f/asyncio-nats-client-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_g/9f_q1hw907s4pdbctf_lj9n19x5s_w/T/pip-install-m4AmzP/asyncio-nats-client/setup.py", line 2, in <module>
        from nats.aio.client import __version__
      File "nats/__init__.py", line 22
        yield from nc.connect(**options)
                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_g/9f_q1hw907s4pdbctf_lj9n19x5s_w/T/pip-install-m4AmzP/asyncio-nats-client/

**Comment by umitanuki** [comment]
Thank you for the suggestion, yes it should be mentioned clearly.
