### ISSUE TITLE
Alpaca/polygon client doesn't obey broker config

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/pylivetrader#29]
Setting keys in env vars works, but config values are ignored.

ValueError: Key ID must be given to access Alpaca trade API

**Comment by umitanuki** [comment]
Turns out this is pipeline-live issue. Currently we don't have vehicle to pass the broker config to pipeline-live...

**Comment by umitanuki** [comment]
I think the issue still persists. It should happen if you don't have environment variable set and use pipeline-live since pylivetrader doesn't pass the API key pipeline-live.

**Comment by garyha** [comment]
yaml worked until i added a polygon import

`from pipeline_live.data.polygon.filters  import IsPrimaryShareEmulation as IsPrimaryShare`

Then had to use environment variables.  : (

**Comment by reedv** [comment]
I notice that the [readme docs](https://github.com/alpacahq/pylivetrader#alpaca), mention how to set the env. vars. for the API keys, but not the API endpoint (eg. for specifying between live and paper trading), should assume that it is the same name as in the config file (only asking because the config. var. and env. var. names for the API keys are named differently)?

**Comment by ttt733** [comment]
@reedv - Thanks for pointing that out; the readme's been updated.

**Comment by sokol11** [comment]
Hey guys. I am just trying out alpaca for the first time today (please don't yell at me). I seem to be experiencing the same problem, trying to log into the API from jupyter/python notebook. It works, if I set the API tokens and base url as environmental variables, but if I pass them to tradeapi.REST() directly, I get "HTTPError: 404 Client Error: Not Found for url: https://paper-api.alpaca.markets//V2/account". Doesn't bother me much as going with environment variables works but feels like it should be addressed somewhere, as for most new users this will be the first point of interaction with alpaca.

**Comment by evyatarlavian** [comment]
> Hey guys. I am just trying out alpaca for the first time today (please don't yell at me). I seem to be experiencing the same problem, trying to log into the API from jupyter/python notebook. It works, if I set the API tokens and base url as environmental variables, but if I pass them to tradeapi.REST() directly, I get "HTTPError: 404 Client Error: Not Found for url: https://paper-api.alpaca.markets//V2/account". Doesn't bother me much as going with environment variables works but feels like it should be addressed somewhere, as for most new users this will be the first point of interaction with alpaca.

you just got a double '/' before the V2. remove one and you'll be good to go

**Comment by shlomikushchi** [comment]
this issue was fixed in this commit: https://github.com/alpacahq/pylivetrader/commit/28ea45a28992400236287002b2aca68c3957bb81

fixed it by setting the env variable in the scenario we use pylivetrader in combination with pipeline-live and when the credentials were passed with a config file.

**Comment by shlomikushchi** [comment]
@sokol11 your issue is not related to this issue.
try pulling the patest source code and let me know if you still have any issues.
