### ISSUE TITLE
Logging timestamp timezone

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/pylivetrader#32]
Should be able to configure and/or based on the system timezone.

**Comment by garyha** [comment]
In pylivetrader, a solution offered does work:

import logbook
import pandas as pd
logbook.set_datetime_format(lambda: pd.Timestamp.now(tz='America/New_York'))

Would be great to be able to simply do:
def initialize(context):
    context.timezone = 'US/Eastern'  # or 'America/New_York'

**Comment by shlomikushchi** [comment]
I am adding 3 options for log timezones:
1. UTC
2. LOCAL
3. NY (America/New_York)

a user will be able decide which one by adding argument to the pylivetrader cli
e.g:
`pylivetrader run macd.py -tz NY`

you could check your options by running:
`pylivetrader run --help`
