### ISSUE TITLE
Conda and/or windows bdist package

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/pylivetrader#39]
There are quite a bit of users on Windows and one of the hardest thing is the setup, especially with pipeline-live which has deep dependency with binary build requirements. As noted in https://docs.alpaca.markets/libraries/pylivetrader-windows/ `lru-dict` requires Visual Studio, which is not very easy to handle.

I'd like to make it as easy as `pip install` or `conda install`. This may need some research on that. bdist_wheel may be enough if it's built on windows?

**Comment by umitanuki** [comment]
@ttt733 please close this if it's done.

**Comment by ttt733** [comment]
Conda builds have been added to the alpacahq channel.
