### ISSUE TITLE
context namespace

### ISSUE THREAD

**Issue by bdowling** [alpacahq/pylivetrader#76]
I ran into an issue with trying to set `context.symbol = 'TIK'`, due to how this is handled in `api_context.api_method()` this isn't supported, and resulted in a problem that was hard to trace down.

Setting `context.symbol` obscured the `symbol()` lookup due to the way the namespaces are munged in `api_method` local redirection.  e.g. it resulted in errors attempting to call a string as a function.

The context.symbol ended up being stored in the pkl file and trying to troubleshoot the issue by changing my code didn't work as the errant context was reloaded.

**Comment by ttt733** [comment]
I tried separating out the namespaces to allow for setting names like `symbol`, but it wasn't as easy as I had hoped. For now, attempts to set something that would collide with an API method will now raise an exception. That should hopefully make it easier to work around for the time being. I'll leave this issue open for now in case anyone gets a chance to handle the context namespace more cleanly. Thanks for bringing this up!

**Comment by shlomikushchi** [comment]
this scenario can make the user get tangled in a non working environment. 
I thought about this as well, maybe defining inside \_\_setattr\_\_ a "user_space" so when setting an attribute we do something like this:
```py
    def __setattr__(self, name, value):
        # Reject names that overlap with API method names
        if hasattr(self, 'api_methods') and name in self.api_methods:
            self.user_space[name] = value  #  <====================
        else:
            object.__setattr__(self, name, value)
```

and change the `__getattr__` accordingly.
but it does not worth the effort.
it is a reasonable limitation - not to use a resereved attribute (in my opinion ofc)

so for now, I am closing this issue with a good enough solution
