### ISSUE TITLE
pylivetrader: command not found

### ISSUE THREAD

**Issue by shinyben** [alpacahq/pylivetrader#95]
I'm using Ubuntu 18.04 on Google Cloud Platform. The commands I use, in order, are:

`sudo apt update`
`sudo apt -y upgrade`
`sudo apt install -y python3-pip`
`python3 -m pip install pylivetrader`
`python3 -m pip install pipeline-live`
`pylivetrader run -f algo.py --backend-config config.yaml`

On the last command, I get `pylivetrader: command not found`

Any ideas?

**Comment by umitanuki** [comment]
What is the log output after `python3 -m pip install pylivetrader`? it may say something where it installs

**Comment by shinyben** [comment]
New error after letting it sit a while:

> Traceback (most recent call last):
>   File "/home/g99bengardner/.local/bin/pylivetrader", line 7, in <module>
>     from pylivetrader.__main__ import main
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pylivetrader/__init__.py", line 16, in <module>
>     from pylivetrader import api # noqa
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pylivetrader/api.py", line 25, in <module>
>     from pylivetrader.finance.asset_restrictions import (
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pylivetrader/finance/asset_restrictions.py", line 20, in <module>
>     import pandas as pd
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
>     from pandas.core.api import *
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
>     from pandas.core.groupby import Grouper
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
>     from pandas.core.groupby.groupby import (
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 48, in <module>
>     from pandas.core.arrays import ExtensionArray, Categorical
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
>     from .base import ExtensionArray  # noqa
>   File "/home/g99bengardner/.local/lib/python3.6/site-packages/pandas/core/arrays/base.py", line 10, in <module>
>     from pandas.errors import AbstractMethodError
> ImportError: cannot import name 'AbstractMethodError'

**Comment by umitanuki** [comment]
Sounds like your env was messed up with library path?

**Comment by shinyben** [comment]
I'm not sure how that happened, as the above were the only commands I used on a clean VM. I'll close this, as I'm moving on to Docker
