### ISSUE TITLE
Docker permission denied

### ISSUE THREAD

**Issue by shinyben** [alpacahq/pylivetrader#96]
Followed accepted answer at https://askubuntu.com/questions/938700/how-do-i-install-docker-on-ubuntu-16-04-lts to get set up.

I'm not familiar with Docker, but am trying to use it as I was having library trouble.

When I run `docker run -v $PWD:/work -w /work alpacamarkets/pylivetrader pylivetrader run -f algo.py`, I get

> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
> See 'docker run --help'.

I also get this error when I run `docker pull alpacamarkets/pylivetrader`.

**Comment by ttt733** [comment]
This does not seem to be a pylivetrader issue. You may need to run `docker login`, or you may need to follow some of the post-install steps here: https://docs.docker.com/install/linux/linux-postinstall/.
