### ISSUE TITLE
Cannot find reference '' in api.py

### ISSUE THREAD

**Issue by Frick-David** [alpacahq/pylivetrader#99]
The code `from pylivetrader.api import (
     order_percent,
     get_datetime,
     get_open_orders,
     cancel_order,
     schedule_function,
     order_target_percent,
     date_rules,
     time_rules,
     symbol)` does not work as half of the imports are not found. Any suggestions as I see most people's code using this library still uses this format.

**Comment by ttt733** [comment]
Hi @FrickProgrammer , I'm not 100% sure what the issue you're seeing is. Could you paste over the full stack trace of the error you're running into, and let me know what your version of pylivetrader is?

**Comment by shlomikushchi** [comment]
closing this issue because there was no new comments for a long time. if anything is still relevant please reopen the issue.
